## NUMPY
NumPy provides an ** N-dimensional array type**, the ndarray, which describes a collection of “items” of the same type. The items can be indexed using for example N integers.

All ndarrays are homogenous: every item takes up the same size block of memory, and all blocks are interpreted in exactly the same way. How each item in the array is to be interpreted is specified by a separate data-type object, one of which is associated with every array. In addition to basic types (integers, floats, etc.), the data type objects can also represent data structures.

An item extracted from an array, e.g., by indexing, is represented by a Python object whose type is one of the array scalar types built in NumPy. The array scalars allow easy manipulation of also more complicated arrangements of data.

## ndarray

An ndarray is a (usually fixed-size) multidimensional container of items of the same type and size. The number of dimensions and items in an array is defined by its *shape*, which is a tuple of N positive integers that specify the sizes of each dimension. The type of items in the array is specified by a separate data-type object (dtype), one of which is associated with each ndarray.

As with other container objects in Python, the contents of an ndarray can be accessed and modified by indexing or slicing the array (using, for example, N integers), and via the methods and attributes of the ndarray.

Different ndarrays can share the same data, so that changes made in one ndarray may be visible in another. That is, an ndarray can be a “view” to another ndarray, and the data it is referring to is taken care of by the “base” ndarray. ndarrays can also be views to memory owned by Python strings or objects implementing the buffer or array interfaces.

  

In [2]:
import numpy as np
print(np.__version__)

1.18.5


In [3]:
#creating  one dimensional array
a=np.array([1,2,3])
b=np.array( [[1,2,3],[11,22,33]])
print("a")
print (a)
print("b")
print(b)


a
[1 2 3]
b
[[ 1  2  3]
 [11 22 33]]


In [4]:
#find the no of dimensions in array
a.ndim


1

In [5]:
#find the shape of array
#which is a tuple of N positive integers that specify the sizes of each dimension.
print("shape", b.shape)
 
print("size", b.size)
print("item size", b.itemsize)

#a.shape
 


shape (2, 3)
size 6
item size 4


In [6]:
a.dtype

dtype('int32')

In [7]:
a*10

array([10, 20, 30])

# Creating Arrays

Easiest way of creating  arrays is using an **array** function.
This accepts many sequence like objects(including other arrays)  and produce
a new numpy array containing the passed data.

In [8]:
#creating with a list
d_lst=[2,4,6,8,10]
a=np.array(d_lst)

In [9]:
print (a)

[ 2  4  6  8 10]


In [10]:
d_lst=[[1,2,3],[4,5,6]]
b=np.array(d_lst)
print(b)

[[1 2 3]
 [4 5 6]]


In [11]:
print(b.ndim)
print(b.dtype)
print(b.shape)
print(b*10)

2
int32
(2, 3)
[[10 20 30]
 [40 50 60]]


# Creating arrays

In [12]:
#create an array using arange
x = np.arange(10)
print(x)
print(x.shape)
print(x.dtype)

[0 1 2 3 4 5 6 7 8 9]
(10,)
int32


In [13]:
#np.random.rand(shape)
x = np.random.rand(2,3)  # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary
x

array([[0.04912974, 0.08888347, 0.42137523],
       [0.00759899, 0.48183054, 0.83005419]])

In [14]:
#create an array using random values
x = np.random.rand(10)
print(x)
print(x.shape)
print(x.dtype)

[0.61661024 0.37597256 0.77500641 0.74924954 0.68528882 0.89236428
 0.41984033 0.44458428 0.09064311 0.29699102]
(10,)
float64


In [15]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[-0.71059605 -1.7923536  -0.88693452]
 [ 0.25556804  2.19409549  0.55673958]
 [ 0.10541096 -0.18689944  0.12401958]
 [ 0.1535829  -1.77996908  1.28537169]]


In [16]:
print("Random integer vector:",np.random.randint(1,100,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

Random integer vector: [23 37 93 68 49 58 37 78 13 75]

Random integer matrix
[[69 76  6 56]
 [28 26 34 17]
 [95 29 83 82]
 [24 38 67 59]]

20 samples drawn from a dice throw: [3 4 5 1 5 6 2 2 1 4 4 5 5 3 4 3 1 5 6 1]


## numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
Return evenly spaced numbers over a specified interval.

Returns num evenly spaced samples, calculated over the interval [start, stop].

The endpoint of the interval can optionally be excluded.

In [17]:
# 21 linearly spaced  numbers between  1 and 5
la=np.linspace(1,5,21)
print(la)

[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8 5. ]


In [18]:
#creation of random values based on logscale 
#numpy.logspace(start,stop,num,endpoint,base, dtype)
#num is number of samples
#endpoint=True means last value will be included in output
#base : default is 10.0
z=np.logspace(1,10, num=5, endpoint=True, base=10.0)
z



array([1.00000000e+01, 1.77827941e+03, 3.16227766e+05, 5.62341325e+07,
       1.00000000e+10])


## Ones and zeros
empty(shape[, dtype, order])	Return a new array of given shape and type, without initializing entries.

empty_like(a[, dtype, order, subok])	Return a new array with the same shape and type as a given array.

eye(N[, M, k, dtype, order])	Return a 2-D array with ones on the diagonal and zeros elsewhere.

identity(n[, dtype])	Return the identity array.

ones(shape[, dtype, order])	Return a new array of given shape and type, filled with ones.

ones_like(a[, dtype, order, subok])	Return an array of ones with the same shape and type as a given array.

zeros(shape[, dtype, order])	Return a new array of given shape and type, filled with zeros.

zeros_like(a[, dtype, order, subok])	Return an array of zeros with the same shape and type as a given array.

full(shape, fill_value[, dtype, order])	Return a new array of given shape and type, filled with fill_value.

full_like(a, fill_value[, dtype, order, subok])	Return a full array with the same shape and type as a given array.

In [19]:
#zeros and ones create array of a given shape
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
#pass a tuple for shape
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
np.zeros((3,6),dtype='int32')

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [23]:
#empty creates an array of the given shape. but filled with uninitialized garbage values
new=np.empty((3,2))
new

array([[0.04912974, 0.08888347],
       [0.42137523, 0.00759899],
       [0.48183054, 0.83005419]])

In [24]:
#use zeros_like  or ones_like
np.ones_like(new)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [25]:
#Return a new array of given shape and type, filled with fill_value.
np.full((3, 5), 8, dtype=int)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [26]:
#arange is numpy range function
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
#can specify datatype too
y=np.arange(3, dtype=np.float)
y

array([0., 1., 2.])

In [28]:
#create identity  array
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [29]:
#if you  need  a specific shape other than square matrix
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [30]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
#if you other than square, you get error
#np.identity(2,3)

# Mathematical methods
add(array1, array2) or use + , 
sub(array1,array2)  or use -, 
multiply(array1,array2)  or use * ,
divide(array1,array2) or use /.

In [32]:
print('Add the two arrays:' )
a=np.arange(9).reshape(3,3)
 
b=np.arange(9).reshape(3,3)
 
print(np.add(a,b))
print("operator +")
print(a+b)
print("operator -")
print(a-b)
 

Add the two arrays:
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
operator +
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
operator -
[[0 0 0]
 [0 0 0]
 [0 0 0]]


## Scalars
Python defines only one type of a particular data class (there is only one integer type, one floating-point type, etc.). This can be convenient in applications that don’t need to be concerned with all the ways data can be represented in a computer. For scientific computing, however, more control is often needed.

In NumPy, there are 24 new fundamental Python types to describe different types of scalars. These type descriptors are mostly based on the types available in the C language that CPython is written in, with several additional types compatible with Python’s types.

Array scalars have the same attributes and methods as ndarrays. This allows one to treat items of an array partly on the same footing as arrays, smoothing out rough edges that result when mixing scalar and array operations

In [33]:
#A NumPy scalar is any object which is an instance of np.generic or whose type is in np.
##operations between arrays any scalars

a=np.ones((2,3))
a *4


array([[4., 4., 4.],
       [4., 4., 4.]])

In [34]:
a*a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [35]:
b=np.array([[1,2,3],[4,5,6]], dtype= 'float32')
b

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [36]:
b*b

array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)

In [37]:
b**0.5

array([[1.       , 1.4142135, 1.7320508],
       [2.       , 2.236068 , 2.4494898]], dtype=float32)

In [38]:
b*10

array([[10., 20., 30.],
       [40., 50., 60.]], dtype=float32)

In [39]:
#changing type of elements
new=b.astype(int)
new

array([[1, 2, 3],
       [4, 5, 6]])

## Single element indexing
Single element indexing for a 1-D array is what one expects. It work exactly like that for other standard Python sequences.
It is 0-based, and accepts negative indices for indexing from the end of the array.

In [40]:
x = np.arange(10)
print(x)
x[2]


[0 1 2 3 4 5 6 7 8 9]


2

In [41]:
x[-2]

8

In [42]:
x.shape = (2,5) # now x is 2-dimensional
print(x)
x[1,3]

[[0 1 2 3 4]
 [5 6 7 8 9]]


8

In [43]:
 x[1,-1]


9

In [44]:
#if one indexes a multidimensional array with fewer indices than dimensions, one gets a subdimensional array
print(x[0])

[0 1 2 3 4]


# slicing 
It is possible to slice and stride arrays to extract arrays of the same number of dimensions, but of different sizes than the original. The slicing and striding works exactly the same way it does for lists and tuples except that they can be applied to multiple dimensions as well. A few examples illustrates best:

In [45]:
x = np.arange(10)


In [46]:
print(x[2:5])
# space out values
print(x[2:7:2])

[2 3 4]
[2 4 6]


Note that slices of arrays do not copy the internal array data but also produce new views of the original data.
# Indexing with other arrays
It is possible to index arrays with other arrays for the purposes of selecting lists of values out of arrays into new arrays. There are two different ways of accomplishing this. One uses one or more arrays of index values. The other involves giving a boolean array of the proper shape to indicate the values to be selected. Index arrays are a very powerful tool that allow one to avoid looping over individual elements in arrays and thus greatly improve performance.

In [47]:
#indexing arrays
x = np.arange(10,1,-1)
print(x)

x[np.array([3, 3, 1, 8])]


[10  9  8  7  6  5  4  3  2]


array([7, 7, 9, 2])

The index array consisting of the values 3, 3, 1 and 8 correspondingly create an array of length 4 (same as the index array) where each index is replaced by the value the index array has in the array being indexed.
Negative values are permitted and work as they do with single indices or slices:

In [48]:


x[np.array([3, 3, -1, 8])]

array([7, 7, 2, 2])

In [49]:
y = np.arange(35).reshape(5,7)
print("Y matrix")
print(y)
print("slice")
print(y[1:5:2,::3])



Y matrix
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]
slice
[[ 7 10 13]
 [21 24 27]]


# Indexing Multi-dimensional arrays
Things become more complex when multidimensional arrays are indexed, particularly with multidimensional index arrays. These tend to be more unusual uses, but they are permitted, and they are useful for some problems. We’ll start with the simplest multidimensional case (using the array y from the previous examples):



  

In [50]:
print("y =",y)
print("indexed")
y[np.array([0,2,4]), np.array([0,1,2])]

y = [[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]
indexed


array([ 0, 15, 30])

In this case, if the index arrays have a matching shape, and there is an index array for each dimension of the array being indexed, the resultant array has the same shape as the index arrays, and the values correspond to the index set for each position in the index arrays. In this example, the first index value is 0 for both index arrays, and thus the first value of the resultant array is y[0,0]. The next value is y[2,1], and the last is y[4,2].

In [51]:
# If the index arrays do not have the same shape, there is an attempt to broadcast them to the same shape.
#If they cannot be broadcast to the same shape, an exception is raised:
print(y.shape)
y[np.array([0,2,4]), np.array([0,1])]


(5, 7)


IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

## Boolean or “mask” index arrays
Boolean arrays used as indices are treated in a different manner entirely than index arrays. Boolean arrays must be of the same shape as the initial dimensions of the array being indexed. In the most straightforward case, the boolean array has the same shape:

In [52]:
y = np.arange(35).reshape(5,7)
print(y)
b=y>24
print("y values > 24")
print(y[b])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]
y values > 24
[25 26 27 28 29 30 31 32 33 34]


Unlike in the case of integer index arrays, in the boolean case, the result is a 1-D array containing all the elements in the indexed array corresponding to all the true elements in the boolean array. The elements in the indexed array are always iterated and returned in row-major (C-style) order.

##  Commonly  used numpy methods

In [53]:
x = np.arange(4)
xx = x.reshape(2,2)
print(x)
print(xx)
print("shape=",xx.shape)
#ravel methods flatten a multidimension array
newarr=np.ravel(xx)
print(newarr)

[0 1 2 3]
[[0 1]
 [2 3]]
shape= (2, 2)
[0 1 2 3]


In [54]:
 np.maximum([2, 3, 4], [1, 5, 2])


array([2, 5, 4])

In [55]:
np.maximum(np.eye(2), [0.5, 2]) # broadcasting

array([[1. , 2. ],
       [0.5, 2. ]])

In [56]:
np.maximum(np.Inf, 1)

inf

In [57]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)
 

array([[4, 1],
       [2, 2]])

In [58]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
b=a.transpose()
print(b)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [63]:
# sort along the  row wise

a = np.array([[12, 15], [10, 1]])
print(a)
arr1 = np.sort(a)  
print(arr1)

[[12 15]
 [10  1]]
[[12 15]
 [ 1 10]]


In [64]:
# sort along the first axis-- columnwise

a = np.array([[12, 15], [10, 1]])
arr1 = np.sort(a, axis = 0)  
print(arr1)

[[10  1]
 [12 15]]


## Difference between list and arrays in python
1.  Size in memory
2. Time for processing

# END